# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='scp.proto',
  package='',
  serialized_pb='\n\tscp.proto\"6\n\x16SfkConnectionPointAuth\x12\r\n\x05token\x18\x01 \x02(\t\x12\r\n\x05\x61ppid\x18\x02 \x02(\t\"$\n\x04Ping\x12\r\n\x05\x63time\x18\x01 \x02(\x03\x12\r\n\x05stime\x18\x02 \x01(\x03\"$\n\x04Pong\x12\r\n\x05\x63time\x18\x01 \x02(\x03\x12\r\n\x05stime\x18\x02 \x01(\x03\"E\n\nSfkContent\x12\x12\n\nidentifier\x18\x01 \x02(\t\x12\x12\n\nrequest_id\x18\x02 \x02(\t\x12\x0f\n\x07headers\x18\x03 \x03(\t\"\xec\x01\n\x03Msg\x12\x1b\n\x05mtype\x18\x01 \x02(\x0e\x32\x0c.Msg.MsgType\x12%\n\x04\x61uth\x18\x02 \x01(\x0b\x32\x17.SfkConnectionPointAuth\x12\x13\n\x04ping\x18\x03 \x01(\x0b\x32\x05.Ping\x12\x13\n\x04pong\x18\x04 \x01(\x0b\x32\x05.Pong\x12\x1c\n\x07\x63ontent\x18\x05 \x01(\x0b\x32\x0b.SfkContent\"Y\n\x07MsgType\x12\x08\n\x04\x41UTH\x10\x01\x12\x08\n\x04PING\x10\x02\x12\x08\n\x04PONG\x10\x03\x12\x0b\n\x07MESSAGE\x10\x04\x12\x0e\n\nSFKCONTENT\x10\x05\x12\x13\n\x0fSESSION_DROPPED\x10\x06')



_MSG_MSGTYPE = descriptor.EnumDescriptor(
  name='MsgType',
  full_name='Msg.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AUTH', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PING', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PONG', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MESSAGE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SFKCONTENT', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SESSION_DROPPED', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=364,
  serialized_end=453,
)


_SFKCONNECTIONPOINTAUTH = descriptor.Descriptor(
  name='SfkConnectionPointAuth',
  full_name='SfkConnectionPointAuth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='token', full_name='SfkConnectionPointAuth.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='appid', full_name='SfkConnectionPointAuth.appid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=13,
  serialized_end=67,
)


_PING = descriptor.Descriptor(
  name='Ping',
  full_name='Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ctime', full_name='Ping.ctime', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stime', full_name='Ping.stime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=105,
)


_PONG = descriptor.Descriptor(
  name='Pong',
  full_name='Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ctime', full_name='Pong.ctime', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stime', full_name='Pong.stime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=107,
  serialized_end=143,
)


_SFKCONTENT = descriptor.Descriptor(
  name='SfkContent',
  full_name='SfkContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='identifier', full_name='SfkContent.identifier', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request_id', full_name='SfkContent.request_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='headers', full_name='SfkContent.headers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=145,
  serialized_end=214,
)


_MSG = descriptor.Descriptor(
  name='Msg',
  full_name='Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mtype', full_name='Msg.mtype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='auth', full_name='Msg.auth', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ping', full_name='Msg.ping', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pong', full_name='Msg.pong', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='Msg.content', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSG_MSGTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=217,
  serialized_end=453,
)

_MSG.fields_by_name['mtype'].enum_type = _MSG_MSGTYPE
_MSG.fields_by_name['auth'].message_type = _SFKCONNECTIONPOINTAUTH
_MSG.fields_by_name['ping'].message_type = _PING
_MSG.fields_by_name['pong'].message_type = _PONG
_MSG.fields_by_name['content'].message_type = _SFKCONTENT
_MSG_MSGTYPE.containing_type = _MSG;
DESCRIPTOR.message_types_by_name['SfkConnectionPointAuth'] = _SFKCONNECTIONPOINTAUTH
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['SfkContent'] = _SFKCONTENT
DESCRIPTOR.message_types_by_name['Msg'] = _MSG

class SfkConnectionPointAuth(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SFKCONNECTIONPOINTAUTH
  
  # @@protoc_insertion_point(class_scope:SfkConnectionPointAuth)

class Ping(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PING
  
  # @@protoc_insertion_point(class_scope:Ping)

class Pong(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PONG
  
  # @@protoc_insertion_point(class_scope:Pong)

class SfkContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SFKCONTENT
  
  # @@protoc_insertion_point(class_scope:SfkContent)

class Msg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG
  
  # @@protoc_insertion_point(class_scope:Msg)

# @@protoc_insertion_point(module_scope)
